### ISSUE TITLE
插件图标

### ISSUE THREAD

**Issue by duccck** [Semibold/Extensions-Steward#14]
插件图标风格可否参照 Chrome 原生的主页图标改一下？放在菜单栏看起来比较违和。

**Comment by Aqours** [comment]
不明白你的意思

**Comment by duccck** [comment]
插件图标相对原生图标线条要粗一些，固定在菜单栏看起来不是很统一。

**Comment by Aqours** [comment]
你的意思时跟![image](https://user-images.githubusercontent.com/8586286/39906319-7d17ced0-5514-11e8-8be7-2605e1ec3237.png)这个比较？

![image](https://user-images.githubusercontent.com/8586286/39906337-97b3954e-5514-11e8-9b67-22ed8c5a606b.png)
扩展看起来没问题。

**Comment by duccck** [comment]
是的，我个人感觉两者看起来有很明显的区别。

**Comment by Aqours** [comment]
(´･_･`) 扩展不和主页的按钮放一起，看起来没什么不妥呀！
如果可以，你可以参考[这个规范](https://developer.chrome.com/webstore/images)设计个图标来看看

**Comment by oknixus** [comment]
哇……原来这个扩展也是国人开发的！好自豪啊！
