### ISSUE TITLE
请问作者小哥哥，这个能两列显示吗？

### ISSUE THREAD

**Issue by oknixus** [Semibold/Extensions-Steward#16]
![image](https://user-images.githubusercontent.com/4592706/48395109-1c6be380-e751-11e8-88c6-c4af8ea6a3c8.png)
把禁用的，和启用的，分开成两列显示，这样，在大部分用户这里，就可以不显示滚动条了，您觉得呢？
![image](https://user-images.githubusercontent.com/4592706/48395151-47eece00-e751-11e8-80e5-536b6d90d303.png)
非常感谢您，开发了很棒的扩展！

**Comment by Aqours** [comment]
分成两列，好坏参半，可以提供选项是否开启分成两列，有时间我加下这个功能。

**Comment by oknixus** [comment]
@Aqours 作者，您好！我突然想到了可能比分成两列更好的方案了！
其实安装了很多插件，很多插件其实是可以进行归类的！
比如开发者用户，他们使用的插件，至少可以分为几类：
1、通用型插件，比如广告拦截、翻译等插件；
2、开发型插件，比如开发工具、postman、JSON格式化等；
3、基于Chrome插件的休闲小游戏，工作之余放松一下；
4、不常用的插件，比如网页截图、OneNote、pocket等；

如果有一个分类的功能，对同一分类的插件，进行统一的启用和关闭，相信比分成两列会更好！
个人愚见，如果觉得不可行，还请勿怪，谢谢！

感谢您提供如此好用的插件管理插件！谢谢！

**Comment by Aqours** [comment]
谢谢你的建议。在此之前，可以搜下商店里有此类功能的扩展没有，如果你有较多的扩展，这个扩展管理器确实不适合。这个扩展是我个人用的，因此不打算做的复杂，同时我也没有额外的时间来做这些事。

**Comment by oknixus** [comment]
找到了可以分组的了！谢谢！
