### ISSUE TITLE
dark mode 下效果焦点显示不佳

### ISSUE THREAD

**Issue by AnabasisXu** [Semibold/Extensions-Steward#18]
使用chrome://flags/ 中的dark mode 之后，很难看得出到底光标在那里。建议改为灰色之外的颜色，如蓝色。
![image](https://user-images.githubusercontent.com/48761002/187053269-875e31cd-363d-4416-a9a4-74d28fa187ce.png)

**Comment by Aqours** [comment]
1. 鼠标是什么颜色？（默认是小手，应该是白色黑边，能看清）
2. 是觉得已禁用的颜色不够明显吗？
3. 鼠标移动到列表项没有外轮廓吗？（如下图所示）
<img width="290" alt="image" src="https://user-images.githubusercontent.com/8586286/187592444-292f4cb5-1a5d-4925-8d99-aeecdb2fd9f8.png">

**Comment by AnabasisXu** [comment]
鼠标是什么颜色？（默认是小手，应该是白色黑边，能看清）
白色，能看清

是觉得已禁用的颜色不够明显吗？
已禁用和已启用的区分度不够高

鼠标移动到列表项没有外轮廓吗？（如下图所示）
没有外轮廓

其实最好是尽量键盘操作。

Steward Plus禁用拓展的操作也很方便，之所以要尝试这个是因为
1 不支持批量禁用，建议增加分组功能。
2 禁用一个之后，光标跳转到顶部，又得重新向下找到下一个要禁用的

**Comment by Aqours** [comment]
> 已禁用和已启用的区分度不够高

这个有空调整一下颜色。

> 没有外轮廓

什么系统及浏览器？目前 macOS、Windows 下的 Chrome 表现都是有的

> 其实最好是尽量键盘操作

可以使用快捷键，也可以搜索，<kbd>tab</kbd>、<kbd>shift+tab</kbd>、<kbd>enter</kbd> 可以选择和选中

> 分组功能

目前没什么空闲时间，不会加这个功能。目前其他扩展有分组、按网站启用、停用功能，需要可以试试
